# Site
repository: sproogen/resume-theme
#favicon: images/favicon.ico

#version: 1

# Personal info
name: Enrichetta Mileti
title: PhD Student
email: enrichetta.mileti@ki.se
website: https://staff.ki.se/people/enrmil
adress: Copenhagen, Denmark

# Social links
twitter_username: EnrichettaM
github_username:  EnrichettaMileti
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: enrichetta-mileti-98013673
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/photo.jpg
about_content: |
  Hi there, my name is Enrichetta. I'm a bioinformatician, studying ...
  In 2012 I got my bachelor degree in Biology at the [University of L'Aquila](https://www.univq.it).
  In the meanwhile, the importance of Bioinformatics in biological analysis has become more and more important and my curiosity in use it as well.
  This prompted me to join the International Master in Bioinformatics in 2013 at [University of Bologna](https://www.unibo.it) and I acquired a master's degree in July 2014.
  In October 2014, I joined the [Carsten Daub group](https://www.daublab.org) as Scientific Trainee and starting from March 2015 I started my PhD journey.
  
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
#educaton_title: Education

# Publications Section
#publications_title: Publications

# More Section
more_title: When I'm Not Programming
more_content: |


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
